[tool.poetry]
name = "dailywire-downloader"
version = "0.1.0"
description = "A tool to download premium shows from the DailyWire website"
authors = ["SamuÃ«l Visser <samuvisser@gmail.com>"]
readme = "README.md"
packages = [{include = "dailywire_downloader"}]

[tool.poetry.dependencies]
python = "~3.13"
pyyaml = "^6.0"
yt-dlp = { git = "https://github.com/yt-dlp/yt-dlp.git", rev = "311bb3b" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"